### PR TITLE
PT-BR Translation

### PR DESCRIPTION
**Pull request by fabianski7**
#31

### CODE REVIEW

**Comment by Ximi1970** [comment]
Great! Thank you. Will merge it a bit later.

**Comment by Ximi1970** [comment]
@fabianski7 could you also translate these new options for closing a window.

- Default close
- Minimize main, close children
- Minimize all windows

No need to fork , just post the translations. I will put them in the files.

Thanks!

**Comment by fabianski7** [comment]
is that translation for that window?



things are a little confusing, the settings inside the firefox and in this window seem to differ a little.

**Comment by Ximi1970** [comment]
Yes that is the one They should be the same now, I hope. Will check it again. I removed the "action" part in the title.

**Pull request merged**
