### PR TITLE
Fixed thunderbird 78.8 window control under openbox wm

### PR DESCRIPTION
**Pull request by trialuser02**

### CODE REVIEW

**Comment by Ximi1970** [comment]
Please tell me what distribution,etc. you are using. It is very difficult to keep everything running for 20+ distributions. 

I really need to check if this does not cause any problems on other window managers. I never expected when I started this add-on the windows managers were such a mess in using the "standard" X11 protocols. So I am extra careful in adding extra state settings and workarounds. It is already one big workaround....  
I did a lot off experiments to get it right for the KDE, GNOME and Xfce in all used version of the distributions, but that was just trying  and hope for the best. :smile: 
Maybe I can setup an extra test distro to check it.

**Comment by trialuser02** [comment]
I'm using Lubuntu 18.04 (openbox + lxde).

**Comment by Ximi1970** [comment]
Your patch was a bit to general to use so I refactored the findWindows() method a bit. Hopefully it can find now the thunderbird window in all window managers.  
I could not test it with openbox because it does not work with Virtualbox.
I tested Systray-X with the default Lubuntu windows manager lxqt? which also did not work the first time. But it looks like it is now working just fine and hopefully it is also working for the openbox wm.  
Could you test this? The code is merged into the develop branch.

**Comment by trialuser02** [comment]
Latest git version works file without this patch.

**Pull request closed without merging**
